<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>VNPTNET.NOM.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Base\Module\FSI.EFCore\FSI.EFCore.csproj" />
    <ProjectReference Include="..\FSI.TestBase\FSI.TestBase.csproj" />
  </ItemGroup>

</Project>
