<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Protos\greet.proto" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Google.Cloud.Translation.V2" Version="3.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
		<PackageReference Include="Microsoft.ML" Version="2.0.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.10.0" />
		<PackageReference Include="Volo.Abp.AutoMapper" Version="5.3.1" />
		<PackageReference Include="Volo.Abp.BackgroundJobs.RabbitMQ" Version="5.3.1" />
		<PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" Version="5.3.1" />
		<PackageReference Include="Volo.Abp.Ddd.Application" Version="5.3.1" />
		<PackageReference Include="Volo.Abp.EventBus.RabbitMQ" Version="5.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\AgoraIO\AgoraIO.csproj" />
		<ProjectReference Include="..\..\Core\FSI.Lib\FSI.Lib.csproj" />
		<ProjectReference Include="..\FSI.Application.Contracts\FSI.Application.Contracts.csproj" />
		<ProjectReference Include="..\FSI.Domain\FSI.Domain.csproj" />
		<ProjectReference Include="..\FSI.GrpcClient\FSI.GrpcClient.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
