version: '3.8'

services:
  #database section
  fsidb:
    image: mysql:8.0.29

  rabbitmq:
    image: rabbitmq:3-management-alpine

  fsi.api:
    image: ${DOCKER_REGISTRY-}fsi-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: Server
      dockerfile: Dockerfile

#network section
networks:
  default:
    name: fsi_microservices
    driver: bridge

#volumes section
volumes:
  fsi_mysql_data:
    name: fsi_mysql_data
  rabbitmq_data:
    name: rabbitmq_data