--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/22/2022 2:34:00 PM
-- Server version: 8.0.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE db_a8d6c0_pj3;

--
-- Drop procedure `Proc_DeleteAccountById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteAccountById;

--
-- Drop procedure `Proc_GetAccountById`
--
DROP PROCEDURE IF EXISTS Proc_GetAccountById;

--
-- Drop procedure `Proc_GetAllAccount`
--
DROP PROCEDURE IF EXISTS Proc_GetAllAccount;

--
-- Drop procedure `Proc_GetNewOrderCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewOrderCode;

--
-- Drop procedure `Proc_InsertAccount`
--
DROP PROCEDURE IF EXISTS Proc_InsertAccount;

--
-- Drop procedure `Proc_UpdateAccount`
--
DROP PROCEDURE IF EXISTS Proc_UpdateAccount;

--
-- Drop procedure `Proc_DeleteOrderById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteOrderById;

--
-- Drop procedure `Proc_GetOrderById`
--
DROP PROCEDURE IF EXISTS Proc_GetOrderById;

--
-- Drop procedure `Proc_GetOrders`
--
DROP PROCEDURE IF EXISTS Proc_GetOrders;

--
-- Drop procedure `Proc_InsertOrder`
--
DROP PROCEDURE IF EXISTS Proc_InsertOrder;

--
-- Drop procedure `Proc_LookupOrder`
--
DROP PROCEDURE IF EXISTS Proc_LookupOrder;

--
-- Drop procedure `Proc_UpdateOrder`
--
DROP PROCEDURE IF EXISTS Proc_UpdateOrder;

--
-- Drop table `order`
--
DROP TABLE IF EXISTS `order`;

--
-- Drop procedure `Proc_DeleteVoucherById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteVoucherById;

--
-- Drop procedure `Proc_GetAllVoucher`
--
DROP PROCEDURE IF EXISTS Proc_GetAllVoucher;

--
-- Drop procedure `Proc_GetVoucherById`
--
DROP PROCEDURE IF EXISTS Proc_GetVoucherById;

--
-- Drop procedure `Proc_InsertVoucher`
--
DROP PROCEDURE IF EXISTS Proc_InsertVoucher;

--
-- Drop procedure `Proc_UpdateVoucher`
--
DROP PROCEDURE IF EXISTS Proc_UpdateVoucher;

--
-- Drop procedure `Proc_UseVoucher`
--
DROP PROCEDURE IF EXISTS Proc_UseVoucher;

--
-- Drop table `voucher`
--
DROP TABLE IF EXISTS voucher;

--
-- Drop procedure `Proc_InsertTokenAccount`
--
DROP PROCEDURE IF EXISTS Proc_InsertTokenAccount;

--
-- Drop table `tokenaccount`
--
DROP TABLE IF EXISTS tokenaccount;

--
-- Drop procedure `Proc_GetItems`
--
DROP PROCEDURE IF EXISTS Proc_GetItems;

--
-- Drop view `view_items`
--
DROP VIEW IF EXISTS view_items CASCADE;

--
-- Drop procedure `Proc_ChangeInStock`
--
DROP PROCEDURE IF EXISTS Proc_ChangeInStock;

--
-- Drop procedure `Proc_DeleteCategoryById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteCategoryById;

--
-- Drop procedure `Proc_DeleteItemById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteItemById;

--
-- Drop procedure `Proc_GetItemById`
--
DROP PROCEDURE IF EXISTS Proc_GetItemById;

--
-- Drop procedure `Proc_GetNewItemCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewItemCode;

--
-- Drop procedure `Proc_InsertItem`
--
DROP PROCEDURE IF EXISTS Proc_InsertItem;

--
-- Drop procedure `Proc_UpdateItem`
--
DROP PROCEDURE IF EXISTS Proc_UpdateItem;

--
-- Drop table `item`
--
DROP TABLE IF EXISTS item;

--
-- Drop procedure `Proc_GetAllCategory`
--
DROP PROCEDURE IF EXISTS Proc_GetAllCategory;

--
-- Drop procedure `Proc_GetCategoryById`
--
DROP PROCEDURE IF EXISTS Proc_GetCategoryById;

--
-- Drop procedure `Proc_InsertCategory`
--
DROP PROCEDURE IF EXISTS Proc_InsertCategory;

--
-- Drop procedure `Proc_UpdateCategory`
--
DROP PROCEDURE IF EXISTS Proc_UpdateCategory;

--
-- Drop table `category`
--
DROP TABLE IF EXISTS category;

--
-- Drop procedure `Proc_GetNotifications`
--
DROP PROCEDURE IF EXISTS Proc_GetNotifications;

--
-- Drop procedure `Proc_InsertNotification`
--
DROP PROCEDURE IF EXISTS Proc_InsertNotification;

--
-- Drop procedure `Proc_SeenAllNotification`
--
DROP PROCEDURE IF EXISTS Proc_SeenAllNotification;

--
-- Drop table `notification`
--
DROP TABLE IF EXISTS notification;

--
-- Drop table `account`
--
DROP TABLE IF EXISTS account;

--
-- Set default database
--
USE db_a8d6c0_pj3;

--
-- Create table `account`
--
CREATE TABLE account (
  AccountId char(36) NOT NULL,
  AccountName varchar(100) NOT NULL,
  Phone varchar(30) NOT NULL,
  Email varchar(50) DEFAULT NULL,
  Password char(200) NOT NULL,
  Role varchar(20) DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (AccountId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Bảng tài khoản';

--
-- Create table `notification`
--
CREATE TABLE notification (
  NotificationId char(36) NOT NULL,
  Content text DEFAULT NULL,
  AccountId char(36) NOT NULL,
  Seen tinyint DEFAULT 0,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (NotificationId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Thông báo';

--
-- Create foreign key
--
ALTER TABLE notification
ADD CONSTRAINT FK_Notification_UserId FOREIGN KEY (AccountId)
REFERENCES account (AccountId);

DELIMITER $$

--
-- Create procedure `Proc_SeenAllNotification`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_SeenAllNotification (IN AccountId char(36))
COMMENT 'Đã xem hết thông báo của 1 tài khoản'
BEGIN
  UPDATE notification n
  SET n.Seen = 1
  WHERE n.AccountId = AccountId
  AND n.Seen = 0;
END
$$

--
-- Create procedure `Proc_InsertNotification`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertNotification (IN Content text, IN AccountId char(36))
COMMENT 'Thêm mới 1 thông báo'
BEGIN
  INSERT INTO notification (NotificationId, Content, AccountId, CreatedAt)
    VALUE (UUID(), Content, AccountId, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetNotifications`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetNotifications (IN Indexx int, IN Count int, IN AccountId char(36), OUT Total int)
COMMENT 'Lấy danh sách thông báo của 1 tài khoản'
BEGIN
  SET @AccountId = AccountId;
  DROP TEMPORARY TABLE IF EXISTS tmpTable;
  IF Count > 0 THEN
    CREATE TEMPORARY TABLE tmpTable AS (SELECT
        *
      FROM notification n
      WHERE n.AccountId = @AccountId);

    SET Total = (SELECT
        COUNT(*)
      FROM tmpTable);
    SELECT
      *
    FROM tmpTable
    ORDER BY tmpTable.CreatedAt DESC LIMIT Indexx, Count;

  END IF;
END
$$

DELIMITER ;

--
-- Create table `category`
--
CREATE TABLE category (
  CategoryId char(36) NOT NULL,
  CategoryCode varchar(40) NOT NULL,
  CategoryName varchar(255) NOT NULL,
  ParentCode varchar(40) DEFAULT NULL,
  IsExpandable tinyint DEFAULT NULL,
  SeftCode int DEFAULT NULL,
  CategoryDescription text DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (CategoryId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Loại mặt hàng';

--
-- Create index `CategoryCode` on table `category`
--
ALTER TABLE category
ADD UNIQUE INDEX CategoryCode (CategoryCode);

DELIMITER $$

--
-- Create procedure `Proc_UpdateCategory`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UpdateCategory (IN CategoryId char(36), IN CategoryName varchar(255), IN IsExpandable boolean, IN CategoryDescription text)
BEGIN
  UPDATE category c
  SET c.CategoryName = CategoryName,
      c.IsExpandable = IsExpandable,
      c.CategoryDescription = CategoryDescription,
      c.ModifiedAt = CURRENT_TIMESTAMP()
  WHERE c.CategoryId = CategoryId;
END
$$

--
-- Create procedure `Proc_InsertCategory`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertCategory (IN CategoryCode varchar(40), IN CategoryName varchar(255), IN ParentCode varchar(40), IN SeftCode int, IN IsExpandable boolean, IN CategoryDescription text)
BEGIN
  INSERT INTO category (CategoryId, CategoryCode, CategoryName, ParentCode, SeftCode, IsExpandable, CategoryDescription, CreatedAt)
    VALUE (UUID(), CategoryCode, CategoryName, ParentCode, SeftCode, IsExpandable, CategoryDescription, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetCategoryById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetCategoryById (IN CategoryId char(36))
BEGIN
  SELECT
    *
  FROM category c
  WHERE c.CategoryId = CategoryId;
END
$$

--
-- Create procedure `Proc_GetAllCategory`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetAllCategory ()
BEGIN
  SELECT
    *
  FROM category c;
END
$$

DELIMITER ;

--
-- Create table `item`
--
CREATE TABLE item (
  ItemId char(36) NOT NULL,
  ItemCode varchar(20) NOT NULL,
  ItemName varchar(255) DEFAULT NULL,
  Description text DEFAULT NULL,
  RealPrice double DEFAULT NULL,
  SaleRate float DEFAULT NULL,
  Medias text DEFAULT NULL,
  Tag varchar(30) DEFAULT NULL,
  CategoryCode varchar(40) DEFAULT NULL,
  InStock int DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (ItemId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Mặt hàng';

--
-- Create index `ItemCode` on table `item`
--
ALTER TABLE item
ADD UNIQUE INDEX ItemCode (ItemCode);

--
-- Create foreign key
--
ALTER TABLE item
ADD CONSTRAINT FK_item_CategoryCode FOREIGN KEY (CategoryCode)
REFERENCES category (CategoryCode) ON DELETE SET NULL ON UPDATE SET NULL;

DELIMITER $$

--
-- Create procedure `Proc_UpdateItem`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UpdateItem (IN ItemId char(36), IN ItemCode varchar(20), IN ItemName varchar(255), IN Description text, IN RealPrice double, IN SaleRate float, IN Medias text, IN Tag varchar(30), IN CategoryCode varchar(40))
BEGIN
  UPDATE item i
  SET i.ItemCode = ItemCode,
      i.ItemName = ItemName,
      i.Description = Description,
      i.RealPrice = RealPrice,
      i.SaleRate = SaleRate,
      i.Medias = Medias,
      i.Tag = Tag,
      i.CategoryCode = CategoryCode,
      i.ModifiedAt = CURRENT_TIMESTAMP()
  WHERE i.ItemId = ItemId;
END
$$

--
-- Create procedure `Proc_InsertItem`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertItem (IN ItemCode varchar(20), IN ItemName varchar(255), IN Description text, IN RealPrice double, IN SaleRate float, IN Medias text, IN Tag varchar(30), IN CategoryCode varchar(40))
BEGIN
  INSERT INTO item (ItemId, ItemCode, ItemName, Description, RealPrice, SaleRate, Medias, Tag, CategoryCode, InStock, CreatedAt)
    VALUE (UUID(), ItemCode, ItemName, Description, RealPrice, SaleRate, Medias, Tag, CategoryCode, 0, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetNewItemCode`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetNewItemCode ()
BEGIN
  SELECT
    CONCAT('SP', (1 + CAST(REPLACE(i.ItemCode, 'SP', '') AS decimal))) AS NewCode
  FROM item i
  ORDER BY (CAST(REPLACE(i.ItemCode, 'SP', '') AS decimal)) DESC LIMIT 0, 1;
END
$$

--
-- Create procedure `Proc_GetItemById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetItemById (IN ItemId char(36))
BEGIN
  SELECT
    *
  FROM item i
  WHERE i.ItemId = ItemId;
END
$$

--
-- Create procedure `Proc_DeleteItemById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_DeleteItemById (IN ItemId char(36))
BEGIN
  DELETE
    FROM item
  WHERE item.ItemId = ItemId;
END
$$

--
-- Create procedure `Proc_DeleteCategoryById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_DeleteCategoryById (IN CategoryId char(36))
BEGIN
  DELETE
    FROM category
  WHERE category.CategoryId = CategoryId;
  UPDATE item i
  SET i.Description = '[]'
  WHERE i.CategoryCode IS NULL;
END
$$

--
-- Create procedure `Proc_ChangeInStock`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_ChangeInStock (IN ChangeNumber int, IN ItemId char(36))
BEGIN
  UPDATE item i
  SET i.InStock = i.InStock + ChangeNumber
  WHERE i.ItemId = ItemId
  AND (i.InStock + ChangeNumber) >= 0;
END
$$

DELIMITER ;

--
-- Create view `view_items`
--
CREATE
DEFINER = 'a8d6c0_pj3'@'%'
VIEW view_items
AS
SELECT
  `i`.`ItemId` AS `ItemId`,
  `i`.`ItemCode` AS `ItemCode`,
  `i`.`ItemName` AS `ItemName`,
  `i`.`Description` AS `Description`,
  `i`.`RealPrice` AS `RealPrice`,
  `i`.`SaleRate` AS `SaleRate`,
  `i`.`InStock` AS `InStock`,
  `i`.`Medias` AS `Medias`,
  `i`.`Tag` AS `Tag`,
  `i`.`CategoryCode` AS `CategoryCode`,
  `c`.`CategoryName` AS `CategoryName`,
  `i`.`CreatedAt` AS `CreatedAt`,
  `i`.`ModifiedAt` AS `ModifiedAt`
FROM (`item` `i`
  LEFT JOIN `category` `c`
    ON ((`i`.`CategoryCode` = `c`.`CategoryCode`)));

DELIMITER $$

--
-- Create procedure `Proc_GetItems`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetItems (IN CategoryCode varchar(40), IN SearchTerms varchar(255), IN Tag varchar(255), IN OrderState int, IN Indexx int, IN Count int, OUT Total int)
BEGIN
  SET @SearchTerms = SearchTerms;
  SET @CategoryCode = CategoryCode;
  SET @Tag = Tag;
  SET @OrderState = OrderState;
  DROP TEMPORARY TABLE IF EXISTS tmpTable;
  IF Count > 0 THEN
    CREATE TEMPORARY TABLE tmpTable AS (SELECT
        *
      FROM view_items i
      WHERE 1 = 1
      AND (
      (
      (
      i.ItemName LIKE CONCAT('%', @SearchTerms, '%')
      OR i.ItemCode LIKE CONCAT('%', @SearchTerms, '%')
      )
      AND @SearchTerms IS NOT NULL
      )
      OR @SearchTerms IS NULL
      )
      AND (
      (
      (
      i.CategoryCode LIKE CONCAT(@CategoryCode, '%')
      )
      AND @CategoryCode IS NOT NULL
      )
      OR @CategoryCode IS NULL
      )
      AND (
      (
      (
      i.Tag LIKE CONCAT('%', @Tag, '%')
      )
      AND @Tag IS NOT NULL
      )
      OR @Tag IS NULL
      ));

    SET Total = (SELECT
        COUNT(*)
      FROM tmpTable);

    IF @OrderState = 1 THEN
      SELECT
        *
      FROM tmpTable
      ORDER BY tmpTable.RealPrice DESC LIMIT Indexx, Count;
    ELSE
      SELECT
        *
      FROM tmpTable
      ORDER BY tmpTable.RealPrice ASC LIMIT Indexx, Count;
    END IF;
  END IF;
END
$$

DELIMITER ;

--
-- Create table `tokenaccount`
--
CREATE TABLE tokenaccount (
  Token varchar(255) NOT NULL,
  Phone varchar(30) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (Token)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'token phiên đăng nhập cho các tài khoản';

DELIMITER $$

--
-- Create procedure `Proc_InsertTokenAccount`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertTokenAccount (IN Token varchar(255), IN Phone varchar(30))
BEGIN
  INSERT INTO tokenaccount (Token, Phone, CreatedAt)
    VALUE (Token, Phone, CURRENT_TIMESTAMP());
END
$$

DELIMITER ;

--
-- Create table `voucher`
--
CREATE TABLE voucher (
  VoucherId char(36) NOT NULL DEFAULT '',
  VoucherCode varchar(30) DEFAULT NULL,
  Description text DEFAULT NULL,
  SaleRate float DEFAULT 0,
  SaleNumber double DEFAULT 0,
  MaxNumber double DEFAULT 0,
  MinTotal double DEFAULT 0,
  Quota int DEFAULT NULL,
  DateExpired datetime DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  IsLimited tinyint DEFAULT NULL,
  PRIMARY KEY (VoucherId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Voucher';

DELIMITER $$

--
-- Create procedure `Proc_UseVoucher`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UseVoucher (IN VoucherId char(36))
BEGIN
  UPDATE voucher v
  SET v.Quota = v.Quota - 1
  WHERE v.VoucherId = VoucherId
  AND v.Quota >= 0;
END
$$

--
-- Create procedure `Proc_UpdateVoucher`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UpdateVoucher (IN VoucherId varchar(36), IN VoucherCode varchar(30), IN Description text, IN SaleRate float, IN SaleNumber double, IN MaxNumber double, IN MinTotal double, IN Quota int, IN DateExpired datetime, IN IsLimited boolean)
BEGIN
  UPDATE voucher v
  SET v.VoucherCode = VoucherCode,
      v.Description = Description,
      v.SaleRate = SaleRate,
      v.SaleNumber = SaleNumber,
      v.MaxNumber = MaxNumber,
      v.MinTotal = MinTotal,
      v.Quota = Quota,
      v.DateExpired = DateExpired,
      V.IsLimited = IsLimited,
      v.ModifiedAt = CURRENT_TIMESTAMP()
  WHERE v.VoucherId = VoucherId;

END
$$

--
-- Create procedure `Proc_InsertVoucher`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertVoucher (IN VoucherCode varchar(30), IN Description text, IN SaleRate float, IN SaleNumber double, IN MaxNumber double, IN MinTotal double, IN Quota int, IN DateExpired datetime, IN IsLimited boolean)
BEGIN
  INSERT INTO voucher (VoucherId, VoucherCode, Description, SaleRate, SaleNumber, MaxNumber, MinTotal, Quota, DateExpired, IsLimited, CreatedAt)
    VALUE (UUID(), VoucherCode, Description, SaleRate, SaleNumber, MaxNumber, MinTotal, Quota, DateExpired, IsLimited, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetVoucherById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetVoucherById (IN VoucherId char(36))
BEGIN
  SELECT
    *
  FROM voucher v
  WHERE v.VoucherId = VoucherId;
END
$$

--
-- Create procedure `Proc_GetAllVoucher`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetAllVoucher ()
BEGIN
  SELECT
    *
  FROM voucher v
  ORDER BY v.CreatedAt DESC;
END
$$

--
-- Create procedure `Proc_DeleteVoucherById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_DeleteVoucherById (IN VoucherId char(36))
BEGIN
  DELETE
    FROM voucher
  WHERE voucher.VoucherId = VoucherId;
END
$$

DELIMITER ;

--
-- Create table `order`
--
CREATE TABLE `order` (
  OrderId char(36) NOT NULL,
  OrderCode varchar(20) DEFAULT NULL,
  BuyerName varchar(255) DEFAULT NULL,
  Phone varchar(30) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  UnitCode varchar(20) DEFAULT NULL,
  Address text DEFAULT NULL,
  Status int DEFAULT NULL,
  PaymentMethod int DEFAULT NULL,
  PaymentStatus tinyint DEFAULT NULL,
  Items text DEFAULT NULL,
  TotalMoney double DEFAULT NULL,
  Ship varchar(255) DEFAULT NULL,
  ShipPayStatus tinyint DEFAULT NULL,
  Note varchar(500) DEFAULT NULL,
  CreatedAt datetime DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  VoucherId char(36) DEFAULT NULL,
  PRIMARY KEY (OrderId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci,
COMMENT = 'Đơn hàng';

DELIMITER $$

--
-- Create procedure `Proc_UpdateOrder`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UpdateOrder (IN OrderId char(36), IN BuyerName varchar(255), IN Phone varchar(30), IN UnitCode varchar(20), IN Address text, IN Status int, IN PaymentMethod int, IN PaymentStatus boolean, IN Items text, IN TotalMoney double, IN Ship varchar(255), IN ShipPayStatus boolean, IN Email varchar(50), IN VoucherId char(36))
BEGIN
  UPDATE `order` o
  SET o.BuyerName = BuyerName,
      o.Phone = Phone,
      o.UnitCode = UnitCode,
      o.Address = Address,
      o.Status = Status,
      o.PaymentMethod = PaymentMethod,
      o.PaymentStatus = PaymentStatus,
      o.Items = Items,
      o.TotalMoney = TotalMoney,
      o.Ship = Ship,
      o.ShipPayStatus = ShipPayStatus,
      o.Email = Email,
      o.VoucherId = VoucherId,
      o.ModifiedAt = CURRENT_TIMESTAMP()
  WHERE o.OrderId = OrderId;
END
$$

--
-- Create procedure `Proc_LookupOrder`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_LookupOrder (IN KeyString varchar(255))
BEGIN
  SELECT
    *
  FROM `order` o
  WHERE o.OrderCode = KeyString
  OR o.Phone = KeyString;
END
$$

--
-- Create procedure `Proc_InsertOrder`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertOrder (IN OrderCode varchar(20), IN BuyerName varchar(255), IN Phone varchar(30), IN UnitCode varchar(20), IN Address text, IN Status int, IN PaymentMethod int, IN Items text, IN TotalMoney double, IN Ship varchar(255), IN ShipPayStatus boolean, IN PaymentStatus boolean, IN Note varchar(500), IN Email varchar(50), IN VoucherId char(36))
BEGIN
  INSERT INTO `order` (OrderId, OrderCode, BuyerName, Phone, UnitCode, Address, Status, PaymentMethod, PaymentStatus, Items, TotalMoney, Ship, ShipPayStatus, Note, Email, VoucherId, CreatedAt)
    VALUE (UUID(), OrderCode, BuyerName, Phone, UnitCode, Address, Status, PaymentMethod, PaymentStatus, Items, TotalMoney, Ship, ShipPayStatus, Note, Email, VoucherId, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetOrders`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetOrders (IN OrderStatus int, IN SearchTerms varchar(255), IN StartTime double, IN EndTime double, IN OrderTimeState int, IN Indexx int, IN Count int, OUT Total int)
COMMENT 'Lấy về danh sách order'
BEGIN
  SET @OrderStatus = OrderStatus;
  SET @SearchTerms = SearchTerms;
  SET @StartTime = StartTime;
  SET @EndTime = EndTime;
  SET @OrderTimeState = OrderTimeState;
  DROP TEMPORARY TABLE IF EXISTS tmpTable;
  IF Count > 0 THEN
    CREATE TEMPORARY TABLE tmpTable AS (SELECT
        *
      FROM `order` o
      WHERE 1 = 1
      AND (
      (
      (
      o.Status = @OrderStatus
      )
      AND @OrderStatus != 0
      )
      OR @OrderStatus = 0
      )
      AND (
      (
      (
      o.OrderCode LIKE CONCAT('%', @SearchTerms, '%')
      OR o.Phone LIKE CONCAT('%', @SearchTerms, '%')
      )
      AND @SearchTerms IS NOT NULL
      )
      OR @SearchTerms IS NULL
      )
      AND (
      UNIX_TIMESTAMP(o.CreatedAt) >= @StartTime
      AND UNIX_TIMESTAMP(o.CreatedAt) <= @EndTime
      ));

    SET Total = (SELECT
        COUNT(*)
      FROM tmpTable);

    IF @OrderTimeState = 1 THEN
      SELECT
        *
      FROM tmpTable
      ORDER BY tmpTable.CreatedAt DESC LIMIT Indexx, Count;
    ELSE
      SELECT
        *
      FROM tmpTable
      ORDER BY tmpTable.CreatedAt ASC LIMIT Indexx, Count;
    END IF;
  END IF;
END
$$

--
-- Create procedure `Proc_GetOrderById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetOrderById (IN OrderId char(36))
BEGIN
  SELECT
    *
  FROM `order` o
  WHERE o.OrderId = OrderId;
END
$$

--
-- Create procedure `Proc_DeleteOrderById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_DeleteOrderById (IN OrderId varchar(36))
BEGIN
  DELETE
    FROM `order`
  WHERE `order`.OrderId = OrderId;
END
$$

--
-- Create procedure `Proc_UpdateAccount`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_UpdateAccount (IN AccountId char(36), IN AccountName varchar(100), IN Phone varchar(30), IN Email varchar(50), IN Password char(200), IN Role varchar(20))
COMMENT 'Cập nhật tài khoản'
BEGIN
  UPDATE account a
  SET a.AccountName = AccountName,
      a.Phone = Phone,
      a.Email = Email,
      a.Password = Password,
      a.Role = Role,
      a.ModifiedAt = CURRENT_TIMESTAMP()
  WHERE a.AccountId = AccountId;
END
$$

--
-- Create procedure `Proc_InsertAccount`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_InsertAccount (IN AccountName varchar(100), IN Phone varchar(30), IN Email varchar(50), IN Password char(200), IN Role varchar(20))
COMMENT 'Thêm mới 1 tài khoản'
BEGIN
  INSERT INTO account (AccountId, AccountName, Phone, Email, Password, Role, CreatedAt)
    VALUES (UUID(), AccountName, Phone, Email, Password, Role, CURRENT_TIMESTAMP());
END
$$

--
-- Create procedure `Proc_GetNewOrderCode`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetNewOrderCode ()
BEGIN
  SET @Random = FLOOR(RAND() * (9999 - 1111 + 1)) + 1111;
  SET @Time = UNIX_TIMESTAMP();
  SELECT
    CONCAT('DH', @Time, @Random) AS NewCode;
END
$$

--
-- Create procedure `Proc_GetAllAccount`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetAllAccount ()
BEGIN
  SELECT
    *
  FROM account a;
END
$$

--
-- Create procedure `Proc_GetAccountById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_GetAccountById (IN AccountId char(36))
COMMENT 'Lấy tài khoản theo id'
BEGIN
  SELECT
    *
  FROM account a
  WHERE a.AccountId = AccountId;
END
$$

--
-- Create procedure `Proc_DeleteAccountById`
--
CREATE DEFINER = 'a8d6c0_pj3'@'%'
PROCEDURE Proc_DeleteAccountById (IN AccountId char(36))
BEGIN
  DELETE
    FROM account
  WHERE account.AccountId = AccountId;
END
$$

DELIMITER ;

-- 
-- Dumping data for table account
--
INSERT INTO account VALUES
('5b6f2ff4-c7c7-11ec-b950-00155e1f4204', 'Nguyễn Văn Hiếu Pro vip', '0971883025', 'vhieukk2000@gmail.com', '$2a$11$zZdJQG/31uBaEst3tAmC0OGAi.H6HU6t9l68N05ElC84r/W9GDx0q', 'admin', '2022-04-29 07:19:18', '2022-04-29 08:22:26'),
('d06295cd-fe5b-11ec-b950-00155e1f4204', 'Nguyễn Bảo Trâm', '0974300198', 'baotram9821@gmail.com', '$2a$11$YGQjhTsm7IoaPm8BXYJucOZQyekiq.YCCQLdXNU8MkhEA/hb18LRa', 'admin', '2022-07-07 18:18:03', NULL);

-- 
-- Dumping data for table category
--
INSERT INTO category VALUES
('04aa5b0b-fe7f-11ec-b950-00155e1f4204', '_3', 'Giày', '', 0, 3, '["Màu sắc","Kích cỡ","Giới tính"]', '2022-07-07 22:30:03', NULL),
('40a5bd18-df32-11ec-b950-00155e1f4204', '_1', 'Áo phông', '', 0, 1, '["Xuất xứ","Chất liệu","Kích cỡ"]', '2022-05-29 02:32:26', NULL),
('6fef863a-df32-11ec-b950-00155e1f4204', '_2', 'Chân váy', '', 0, 2, '["Xuất xứ","Chất liệu","Size"]', '2022-05-29 02:33:46', NULL);

-- 
-- Dumping data for table voucher
--
INSERT INTO voucher VALUES
('0d4386b1-fe83-11ec-b950-00155e1f4204', 'GẺGERG', 'Khuyến mãi 23% tối đa 100đ cho đơn giá tối thiểu 500đ', 0.23, 0, 100, 500, 0, '2022-07-08 05:58:52', '2022-07-07 22:58:55', NULL, 0),
('5bc64806-ca2c-11ec-b950-00155e1f4204', 'SALE2024', 'Khuyến mãi 80000đ cho đơn giá tối thiểu 100000đ', 0, 80000, 0, 100000, 97, '2022-04-19 22:24:00', '2022-05-02 08:27:20', '2022-05-04 03:15:24', 1),
('74dec9ed-13cc-11ed-b950-00155e1f4204', 'HUST2022', 'Khuyến mãi 100000đ cho đơn giá tối thiểu 100000đ', 0, 100000, 0, 100000, 1, '2023-01-01 15:06:00', '2022-08-04 01:07:17', NULL, 0),
('929ba74b-ca2d-11ec-b950-00155e1f4204', 'NEWSALE', 'Khuyến mãi 25000đ cho đơn giá tối thiểu 200000đ', 0, 25000, 0, 200000, 0, '2022-07-19 22:35:00', '2022-05-02 08:36:02', '2022-06-24 08:45:20', 1),
('b9762eef-ca2c-11ec-b950-00155e1f4204', 'SALE2025', 'Khuyến mãi 40% tối đa 50000đ cho đơn giá tối thiểu 250000đ', 0.4, 0, 50000, 250000, 4, '2024-02-02 13:00:00', '2022-05-02 08:29:58', '2022-07-01 19:27:49', 0),
('c9c224ba-fe7f-11ec-b950-00155e1f4204', 'SALE2022', 'Khuyến mãi 20% tối đa 50000đ cho đơn giá tối thiểu 300000đ', 0.2, 0, 50000, 300000, 20, '2022-07-10 12:35:00', '2022-07-07 22:35:34', NULL, NULL);

-- 
-- Dumping data for table tokenaccount
--
INSERT INTO tokenaccount VALUES
('bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjA5NzE4ODMwMDAiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE2NTcxMjE4MjYsImV4cCI6MTY1OTcxMzgyNiwiaWF0IjoxNjU3MTIxODI2fQ.UQDbGIDRM0MapUOQlPspfm48Jz2heYuNjvXOynATUio', '0971883000', NULL, '2022-07-06 08:37:06', NULL),
('bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjA5NzE4ODMwMDEiLCJyb2xlIjoiY3VzdG9tZXIiLCJuYmYiOjE2NTEzMjQ0NTksImV4cCI6MTY1MzkxNjQ1OSwiaWF0IjoxNjUxMzI0NDU5fQ.FidvX1k9Qu3fWdtk4Oiysc8GnAW7dKwCMIKuOxLdnS4', '0971883001', NULL, '2022-04-30 06:14:19', NULL),
('bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjA5NzE4ODMwMjUiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE2NjMzODU5NjYsImV4cCI6MTY2NTk3Nzk2NiwiaWF0IjoxNjYzMzg1OTY2fQ.BwQwH316DOZP-GOW8tmUINreZaHNgmJsPKi-a_zNljA', '0971883025', NULL, '2022-09-16 20:39:27', NULL);

-- 
-- Dumping data for table `order`
--
INSERT INTO `order` VALUES
('0cc68289-f9ad-11ec-b950-00155e1f4204', 'DH16567281829385', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|8|340|', '423423', 1, 1, 0, '7|020745c6-f312-11ec-b950-00155e1f4204|420000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 370000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '4234234', '2022-07-01 19:16:58', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('0d51a115-f887-11ec-b950-00155e1f4204', 'DH16566019453511', 'Nguyễn Văn Hiếu', '0971883025', 'efootball20000@gmail.com', '|31|304|11338|', 'jsjsjsjsjsj', 1, 1, 0, '2|3aa8ac96-efb8-11ec-b950-00155e1f4204|120000|SP1005_0|Áo phông con gấu LV (đen, trắng, xanh lá cây) _and_ 2|24b5d3c6-efba-11ec-b950-00155e1f4204|120000|SP1011_0|Áo phông BEARBRICK đen đỏ trắng _and_ 1|2076ad22-efb9-11ec-b950-00155e1f4204|60000|SP1007_0|Áo phông hình pug _and_ 2|4fcf91d0-f311-11ec-b950-00155e1f4204|120000|SP1029_0|Áo phông GUCCI màu xanh tươi mát', 410000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'jjdjsjjsjsjsjdjdjdjdj', '2022-06-30 08:12:26', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('1177ea96-f7cf-11ec-b950-00155e1f4204', 'DH16565229253259', 'Trịnh Trung', '0971883025', 'utngo007@gmail.com', '|14|118|3712|', 'đường tăng tạm', 3, 1, 0, '7|020745c6-f312-11ec-b950-00155e1f4204|420000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 410000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'đơn côi', '2022-06-29 10:15:26', '2022-07-07 20:25:53', 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('1842c4bc-107d-11ed-b950-00155e1f4204', 'DH16592364971449', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|26|718|', 'ccr3er', 1, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|300000|SP1002_0|Chân váy xếp ly 2 tầng', 250000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'rc', '2022-07-30 20:01:38', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('1ddb27c1-faac-11ec-b950-00155e1f4204', 'DH16568377679066', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|2|29|874|', 'e423423', 1, 1, 0, '14|1f1a2a09-df34-11ec-b950-00155e1f4204|2100000|SP1002_0|Chân váy xếp ly 2 tầng', 2100000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '42342342343243423', '2022-07-03 01:42:48', NULL, '00000000-0000-0000-0000-000000000000'),
('34e108b0-f9ae-11ec-b950-00155e1f4204', 'DH16567287138092', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|27|793|', '42423234', 1, 1, 0, '12|56917ea3-efbb-11ec-b950-00155e1f4204|720000|SP1016_0|Áo phông trắng 3 con BEARBRICK', 670000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '324234234234', '2022-07-01 19:25:14', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('3ae7e5a9-f885-11ec-b950-00155e1f4204', 'DH16566011626797', 'Nguyễn Văn Hiếu', '0971883025', 'utngo007@gmail.com', '|17|148|4801|', '5016546515', 1, 1, 0, '1|020745c6-f312-11ec-b950-00155e1f4204|60000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen _and_ 1|56917ea3-efbb-11ec-b950-00155e1f4204|60000|SP1016_0|Áo phông trắng 3 con BEARBRICK _and_ 1|7b519587-f30f-11ec-b950-00155e1f4204|60000|SP1019_0|Áo phông mèo Tom _and_ 1|82a7b144-f312-11ec-b950-00155e1f4204|60000|SP1033_2|Áo phông gấu bông louis vuitton', 230000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '5048401115350', '2022-06-30 07:59:24', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('426058f6-faac-11ec-b950-00155e1f4204', 'DH16568378293456', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|1|6|202|', '5434534', 1, 1, 0, '9|020745c6-f312-11ec-b950-00155e1f4204|540000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 540000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '5345345343453453', '2022-07-03 01:43:49', NULL, '00000000-0000-0000-0000-000000000000'),
('582123e9-faac-11ec-b950-00155e1f4204', 'DH16568378659714', 'Nguyễn Văn Hiếu', '0971883025', 'utngo007@gmail.com', '|1|17|460|', 'e234342', 1, 1, 0, '2|020745c6-f312-11ec-b950-00155e1f4204|120000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 120000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, '234234324324', '2022-07-03 01:44:26', NULL, '00000000-0000-0000-0000-000000000000'),
('58bdca66-fa27-11ec-b950-00155e1f4204', 'DH16567807434303', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|27|775|', '4234234', 1, 1, 0, '6|b93fb167-f311-11ec-b950-00155e1f4204|900000|SP1031_0|Chân váy ngắn xếp tầng 2 màu trắng đen', 875000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '3243223433', '2022-07-02 09:52:24', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('5e9d7879-f9ac-11ec-b950-00155e1f4204', 'DH16567279246730', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|29|874|', 'đường tăng', 1, 1, 0, '6|2076ad22-efb9-11ec-b950-00155e1f4204|360000|SP1007_0|Áo phông hình pug', 310000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '123454563', '2022-07-01 19:12:05', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('5f7347dc-fe66-11ec-b950-00155e1f4204', 'DH16572476165983', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|11|100|3358|', 'đường vào tim em', 1, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|150000|SP1002_0|Chân váy xếp ly 2 tầng _and_ 1|0316827f-f311-11ec-b950-00155e1f4204|60000|SP1027_0|Áo phông hình gấu bông 2 màu trắng, đen _and_ 3|2076ad22-efb9-11ec-b950-00155e1f4204|180000|SP1007_0|Áo phông hình pug', 365000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'giao trong tuần', '2022-07-07 19:33:38', '2022-07-07 20:15:32', '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('6461b01b-f87e-11ec-b950-00155e1f4204', 'DH16565982266993', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|11|102|3313|', 'sádasd', 1, 1, 0, '6|1cdacec4-efbb-11ec-b950-00155e1f4204|360000|SP1015_0|Áo phông đen hình chó pug', 335000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'sadasdadds', '2022-06-30 07:10:27', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('7466b9cf-fe6c-11ec-b950-00155e1f4204', 'DH16572502295588', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|6|202|', '5435cv3454', 4, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|150000|SP1002_0|Chân váy xếp ly 2 tầng', 150000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, '455c34344', '2022-07-07 20:17:10', '2022-07-07 20:23:20', '00000000-0000-0000-0000-000000000000'),
('764e3b36-faac-11ec-b950-00155e1f4204', 'DH16568379164835', 'Nguyễn Văn Hiếu', '0833368602', 'utngo007@gmail.com', '|11|102|3310|', '5354345345', 1, 1, 0, '1|020745c6-f312-11ec-b950-00155e1f4204|60000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 60000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, '435534534534t4ggv4t', '2022-07-03 01:45:16', NULL, '00000000-0000-0000-0000-000000000000'),
('840eee3d-f9ac-11ec-b950-00155e1f4204', 'DH16567279884368', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|8|340|', '24324324', 1, 1, 0, '10|1cdacec4-efbb-11ec-b950-00155e1f4204|600000|SP1015_0|Áo phông đen hình chó pug', 600000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '4234324324234', '2022-07-01 19:13:08', NULL, '00000000-0000-0000-0000-000000000000'),
('8e9abd90-f880-11ec-b950-00155e1f4204', 'DH16565991554001', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|11|103|3165|', 'hiếu pro', 1, 1, 0, '1|24b5d3c6-efba-11ec-b950-00155e1f4204|60000|SP1011_0|Áo phông BEARBRICK đen đỏ trắng _and_ 3|594fec59-efb7-11ec-b950-00155e1f4204|180000|SP1003_0|Áo phông NICOLAS _and_ 1|7296d531-efb9-11ec-b950-00155e1f4204|60000|SP1008_0|Áo phông đen ba con gấu nâu _and_ 1|7b519587-f30f-11ec-b950-00155e1f4204|60000|SP1019_0|Áo phông mèo Tom', 350000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '12323425423542353245', '2022-06-30 07:25:57', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('8fdfa062-fb35-11ec-b950-00155e1f4204', 'DH16568967992467', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|27|775|', 'hello world', 1, 1, 0, '1|1cdacec4-efbb-11ec-b950-00155e1f4204|60000|SP1015_0|Áo phông đen hình chó pug _and_ 1|83b020f1-f311-11ec-b950-00155e1f4204|60000|SP1030_0|Áo phông GUCCI hình gấu bông hai màu trắng đen cá tính _and_ 2|7b519587-f30f-11ec-b950-00155e1f4204|120000|SP1019_0|Áo phông mèo Tom', 240000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '123', '2022-07-03 18:06:40', NULL, '00000000-0000-0000-0000-000000000000'),
('95e10ff7-fe8c-11ec-b950-00155e1f4204', 'DH16572640299715', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|17|159|5392|', 'aloxo', 1, 1, 0, '2|29f97a99-f311-11ec-b950-00155e1f4204|120000|SP1028_0|Áo phông đen gấu style _and_ 1|508ed10c-f310-11ec-b950-00155e1f4204|60000|SP1023_0|Áo phông hồng', 180000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, '1221', '2022-07-08 00:07:10', NULL, '00000000-0000-0000-0000-000000000000'),
('9893ed5e-f9ae-11ec-b950-00155e1f4204', 'DH16567288819428', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|6|199|', 'ưeqwe', 1, 1, 0, '5|539c7a40-f30f-11ec-b950-00155e1f4204|300000|SP1018_0|Áo phông đen gấu bông nâu', 275000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'ewr345345', '2022-07-01 19:28:02', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('a426a07c-f9ac-11ec-b950-00155e1f4204', 'DH16567280414758', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|8|340|', '423423', 1, 1, 0, '7|020745c6-f312-11ec-b950-00155e1f4204|420000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen', 370000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '4234234', '2022-07-01 19:14:02', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('ab4cc5fe-fe7e-11ec-b950-00155e1f4204', 'DH16572580529336', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|11|94|3133|', 'dfsdf', 1, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|150000|SP1002_0|Chân váy xếp ly 2 tầng _and_ 1|4fcf91d0-f311-11ec-b950-00155e1f4204|60000|SP1029_0|Áo phông GUCCI màu xanh tươi mát', 185000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, '45345', '2022-07-07 22:27:33', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('b3a57c31-f9b2-11ec-b950-00155e1f4204', 'DH16567306444326', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|6|202|', 'qeqweqwe', 1, 1, 0, '4|594fec59-efb7-11ec-b950-00155e1f4204|240000|SP1003_0|Áo phông NICOLAS', 215000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'ưeqwewq', '2022-07-01 19:57:25', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('b68f2fed-f889-11ec-b950-00155e1f4204', 'DH16566030882408', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|6|202|', 'đường đi đâu', 1, 1, 0, '1|82a7b144-f312-11ec-b950-00155e1f4204|60000|SP1033_2|Áo phông gấu bông louis vuitton _and_ 1|7b519587-f30f-11ec-b950-00155e1f4204|60000|SP1019_0|Áo phông mèo Tom _and_ 3|769bc6c5-f310-11ec-b950-00155e1f4204|180000|SP1024_0|Áo phông hồng 3 con gấu bông', 275000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'ghi chú 1', '2022-06-30 08:31:29', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('bace3f1d-f885-11ec-b950-00155e1f4204', 'DH16566013782787', 'Trịnh Trung', '0833368602', 'utngo007@gmail.com', '|89|889|30484|', 'ttvervtertet', 1, 1, 0, '5|1bb5fd0d-f30f-11ec-b950-00155e1f4204|300000|SP1017_0|Áo phông ABC hai màu đen hoặc trắng', 275000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'ểtrterterteterer', '2022-06-30 08:02:59', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('c291a261-fab4-11ec-b950-00155e1f4204', 'DH16568414792598', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|3|109|', '34fsdfsdfsdf3', 1, 1, 0, '18|1bb5fd0d-f30f-11ec-b950-00155e1f4204|1080000|SP1017_0|Áo phông ABC hai màu đen hoặc trắng', 1080000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '23rfdfsdf4f', '2022-07-03 02:44:40', NULL, '00000000-0000-0000-0000-000000000000'),
('cdb94271-0968-11ed-b950-00155e1f4204', 'DH16584581244605', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|1|8|325|', '4 kim đồng', 1, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|300000|SP1002_0|Chân váy xếp ly 2 tầng _and_ 2|2076ad22-efb9-11ec-b950-00155e1f4204|120000|SP1007_0|Áo phông hình pug', 420000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'giao liền', '2022-07-21 19:48:45', NULL, '00000000-0000-0000-0000-000000000000'),
('d219edce-f91d-11ec-b950-00155e1f4204', 'DH16566667003008', 'Trịnh Quang Trung', '0833368602', 'utngo007@gmail.com', '|1|6|199|', 'dá', 1, 1, 0, '1|1f1a2a09-df34-11ec-b950-00155e1f4204|150000|SP1002_0|Chân váy xếp ly 2 tầng', 150000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 0, 'ads', '2022-07-01 02:11:41', NULL, '00000000-0000-0000-0000-000000000000'),
('e44383e9-f881-11ec-b950-00155e1f4204', 'DH16565997291732', 'Nguyễn Văn Hiếu', '0971883025', 'vhieukk20000@gmail.com', '|11|102|3256|', 'qrwrterertyeryrtyrtyrutyutyuty', 1, 1, 0, '8|2076ad22-efb9-11ec-b950-00155e1f4204|480000|SP1007_0|Áo phông hình pug', 470000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '4564ytry45y54g45vgyy5b56ub6j756j', '2022-06-30 07:35:30', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('ef9a92fe-fb91-11ec-b950-00155e1f4204', 'DH16569364747812', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|2|27|775|', 'r34c3244', 1, 1, 0, '7|1f1a2a09-df34-11ec-b950-00155e1f4204|1050000|SP1002_0|Chân váy xếp ly 2 tầng', 1000000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, '423423423', '2022-07-04 05:07:55', NULL, 'b9762eef-ca2c-11ec-b950-00155e1f4204'),
('f87f71d8-f880-11ec-b950-00155e1f4204', 'DH16565993325092', 'Nguyễn Văn Hiếu', '0833368602', 'vhieukk20000@gmail.com', '|14|127|4231|', 'ádwetertr', 1, 1, 0, '1|020745c6-f312-11ec-b950-00155e1f4204|60000|SP1032_0|Áo phông in hình gấu con dễ thương màu đen _and_ 1|24b5d3c6-efba-11ec-b950-00155e1f4204|60000|SP1011_0|Áo phông BEARBRICK đen đỏ trắng _and_ 1|2076ad22-efb9-11ec-b950-00155e1f4204|60000|SP1007_0|Áo phông hình pug _and_ 1|1cdacec4-efbb-11ec-b950-00155e1f4204|60000|SP1015_0|Áo phông đen hình chó pug _and_ 1|1bb5fd0d-f30f-11ec-b950-00155e1f4204|60000|SP1017_0|Áo phông ABC hai màu đen hoặc trắng _and_ 1|29f97a99-f311-11ec-b950-00155e1f4204|60000|SP1028_0|Áo phông đen gấu style _and_ 1|3aa8ac96-efb8-11ec-b950-00155e1f4204|60000|SP1005_0|Áo phông con gấu LV (đen, trắng, xanh lá cây)', 395000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'yuiuyuyuiyuiyuiuiyu', '2022-06-30 07:28:55', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204'),
('f9bfbb82-f954-11ec-b950-00155e1f4204', 'DH16566903894360', 'Văn Hiếu Nguyễn', '0971883025', 'vhieukk20000@gmail.com', '|1|3|103|', 'mon776bu4gguv6', 1, 1, 0, '8|3aa8ac96-efb8-11ec-b950-00155e1f4204|480000|SP1005_0|Áo phông con gấu LV (đen, trắng, xanh lá cây)', 455000, 'Đơn hàng trên 200k sẽ được free ship! Hàng sẽ được giao từ 2-7 ngày tùy nơi đặt.', 1, 'bsdfsdf', '2022-07-01 08:46:30', NULL, '929ba74b-ca2d-11ec-b950-00155e1f4204');

-- 
-- Dumping data for table notification
--
-- Table db_a8d6c0_pj3.notification does not contain any data (it is empty)

-- 
-- Dumping data for table item
--
INSERT INTO item VALUES
('020745c6-f312-11ec-b950-00155e1f4204', 'SP1032', 'Áo phông in hình gấu con dễ thương màu đen', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1032_0', 'sale', '_1', 0, '2022-06-23 09:32:01', NULL),
('0316827f-f311-11ec-b950-00155e1f4204', 'SP1027', 'Áo phông hình gấu bông 2 màu trắng, đen', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1027_0 SP1027_1', 'new hot sale', '_1', 5, '2022-06-23 09:24:53', NULL),
('1bb5fd0d-f30f-11ec-b950-00155e1f4204', 'SP1017', 'Áo phông ABC hai màu đen hoặc trắng', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1017_0 SP1017_1', 'new', '_1', 0, '2022-06-23 09:11:15', '2022-06-23 09:32:55'),
('1cdacec4-efbb-11ec-b950-00155e1f4204', 'SP1015', 'Áo phông đen hình chó pug', '["Trung Quốc","Vai cotton","Over size"]', 100000, 40, 'SP1015_0', 'sale', '_1', 5, '2022-06-19 03:32:26', '2022-06-30 09:57:28'),
('1f1a2a09-df34-11ec-b950-00155e1f4204', 'SP1002', 'Chân váy xếp ly 2 tầng', '["Trung Quốc","Vải","Size S,M,L"]', 200000, 25, 'SP1002_0', 'new hot sale', '_2', 1, '2022-05-29 02:45:49', '2022-08-04 01:14:36'),
('2076ad22-efb9-11ec-b950-00155e1f4204', 'SP1007', 'Áo phông hình pug', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1007_0', 'new', '_1', 1, '2022-06-19 03:18:13', NULL),
('24b5d3c6-efba-11ec-b950-00155e1f4204', 'SP1011', 'Áo phông BEARBRICK đen đỏ trắng', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1011_0', 'hot sale', '_1', 6, '2022-06-19 03:25:30', NULL),
('29f97a99-f311-11ec-b950-00155e1f4204', 'SP1028', 'Áo phông đen gấu style', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1028_0', 'new sale', '_1', 4, '2022-06-23 09:25:58', NULL),
('3aa8ac96-efb8-11ec-b950-00155e1f4204', 'SP1005', 'Áo phông con gấu LV (đen, trắng, xanh lá cây)', '["Trung Quốc","Vải cotton","Over size"]', 100000, 40, 'SP1005_0', 'hot sale', '_1', 6, '2022-06-19 03:11:47', NULL),
('508ed10c-f310-11ec-b950-00155e1f4204', 'SP1023', 'Áo phông hồng', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1023_0', 'new sale', '_1', 5, '2022-06-23 09:19:53', NULL),
('539c7a40-f30f-11ec-b950-00155e1f4204', 'SP1018', 'Áo phông đen gấu bông nâu', '["Trung Quốc","Vải cotton","Free size"]', 100000, 40, 'SP1018_0', 'new hot sale', '_1', 6, '2022-06-23 09:12:49', NULL),
('56917ea3-efbb-11ec-b950-00155e1f4204', 'SP1016', 'Áo phông trắng 3 con BEARBRICK', '["Trung Quốc","Vải cotton","Over size"]', 100000, 40, 'SP1016_0', 'hot', '_1', 6, '2022-06-19 03:34:03', NULL),
('594fec59-efb7-11ec-b950-00155e1f4204', 'SP1003', 'Áo phông NICOLAS', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1003_0', 'new', '_1', 2, '2022-06-19 03:05:29', NULL),
('7296d531-efb9-11ec-b950-00155e1f4204', 'SP1008', 'Áo phông đen ba con gấu nâu', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1008_0', 'new hot sale', '_1', 6, '2022-06-19 03:20:31', NULL),
('769bc6c5-f310-11ec-b950-00155e1f4204', 'SP1024', 'Áo phông hồng 3 con gấu bông', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1024_0', 'new hot sale', '_1', 6, '2022-06-23 09:20:57', NULL),
('7b519587-f30f-11ec-b950-00155e1f4204', 'SP1019', 'Áo phông mèo Tom', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1019_0', 'hot sale', '_1', 4, '2022-06-23 09:13:56', NULL),
('82a7b144-f312-11ec-b950-00155e1f4204', 'SP1033', 'Áo phông gấu bông louis vuitton', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1033_2 SP1033_0 SP1033_1 SP1033_3', 'sale', '_1', 6, '2022-06-23 09:35:36', NULL),
('83b020f1-f311-11ec-b950-00155e1f4204', 'SP1030', 'Áo phông GUCCI hình gấu bông hai màu trắng đen cá tính', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1030_0', 'hot', '_1', 5, '2022-06-23 09:28:29', NULL),
('84291f1b-efba-11ec-b950-00155e1f4204', 'SP1012', 'Áo phông trắng họa tiết đơn giản', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1012_0', 'new', '_1', 6, '2022-06-19 03:28:10', NULL),
('9ee71031-f310-11ec-b950-00155e1f4204', 'SP1025', 'Áo phông gấu bông 3 màu đen, trắng, nâu', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1025_0', 'new hot', '_1', 6, '2022-06-23 09:22:05', NULL),
('9eeeddd4-f30f-11ec-b950-00155e1f4204', 'SP1020', 'Áo phông đen gấu hồng dễ thương', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1020_0', 'new sale', '_1', 6, '2022-06-23 09:14:55', NULL),
('ab9df8ce-efb9-11ec-b950-00155e1f4204', 'SP1009', 'Áo phông trắng gấu con đeo kính dễ thương', '["Trung Quốc","Vải cotton","Over size"]', 100000, 40, 'SP1009_0', 'hot sale', '_1', 6, '2022-06-19 03:22:06', NULL),
('b93fb167-f311-11ec-b950-00155e1f4204', 'SP1031', 'Chân váy ngắn xếp tầng 2 màu trắng đen', '["Trung quốc","Vải cotton","Nữ 40-50 kg"]', 200000, 25, 'SP1031_0', 'new hot sale', '_2', 0, '2022-06-23 09:29:58', NULL),
('bc2cff08-efba-11ec-b950-00155e1f4204', 'SP1013', 'Áo phông trắng BEARBRICK dior', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1013_0', 'new sale', '_1', 6, '2022-06-19 03:29:44', NULL),
('c43a9b3c-efb7-11ec-b950-00155e1f4204', 'SP1004', 'Áo phông RUGAL con gấu', '["Trung Quốc","Vải cotton","Over Size"]', 100000, 40, 'SP1004_0', 'new sale', '_1', 6, '2022-06-19 03:08:29', NULL),
('ca6dfa41-f30f-11ec-b950-00155e1f4204', 'SP1021', 'Áo phông BURBERRY', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1021_0', 'new sale', '_1', 6, '2022-06-23 09:16:08', NULL),
('ccf1d0cb-efb8-11ec-b950-00155e1f4204', 'SP1006', 'Áo phông trắng hình con gấu mặc áo phông đen', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1006_0', 'hot', '_1', 6, '2022-06-19 03:15:53', NULL),
('cee2aacf-f310-11ec-b950-00155e1f4204', 'SP1026', 'Áo phông chanel 3 màu xanh, trắng, đen', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1026_0', 'new sale', '_1', 6, '2022-06-23 09:23:25', NULL),
('d4909c1e-efb9-11ec-b950-00155e1f4204', 'SP1010', 'Áo phông hồng MOSCHINO', '["Trung quốc","Vải cotton","Over size"]', 100000, 40, 'SP1010_0', 'new sale', '_1', 6, '2022-06-19 03:23:15', NULL),
('e03fc6ac-efba-11ec-b950-00155e1f4204', 'SP1014', 'Áo phông gấu đen vàng', '["Trung Quốc","Vải cotton","Over size"]', 100000, 40, 'SP1014_0', 'hot sale', '_1', 6, '2022-06-19 03:30:44', NULL),
('f9ec8f70-f30f-11ec-b950-00155e1f4204', 'SP1022', 'Áo phông MOSCHINO đen, trắng, nâu', '["Trung quốc","Vải cotton","Free size"]', 100000, 40, 'SP1022_0', 'sale', '_1', 6, '2022-06-23 09:17:28', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;